name: "Add community"
description: "Propose a community to add to the _communities collection"
title: "Add community: <name>"
labels: ["community:proposal"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: The public name of the community.
      placeholder: e.g., Mindful Miles
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL
      description: Must start with http:// or https://
      placeholder: https://example.org
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: An official tagline or brief description of the community pulled from a reliable source (e.g., website, social media profile, etc.)
      placeholder: One-liner describing the community.
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags to categorize this community (optional). Use namespaces like "type/coworking-space" or "for/social-good".
      placeholder: e.g., type/coworking-space, for/startups, location/downtown
    validations:
      required: false
