name: Add Community from Issue

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write
  issues: read

concurrency:
  group: add-community-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  propose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure data file exists and is a YAML array
        run: |
          mkdir -p _data
          [ -f _data/communities.yml ] || echo "[]" > _data/communities.yml
          yq -e 'tag == "!!seq"' _data/communities.yml >/dev/null || { echo "_data/communities.yml must be a YAML array"; exit 1; }

      - name: Install yq
        uses: mikefarah/yq@v4.44.3

      - name: Parse Issue Form
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/add_community.yml

      - name: Validate fields
        run: |
          NAME="${{ steps.issue-parser.outputs.issueparser_name }}"
          URL="${{ steps.issue-parser.outputs.issueparser_url }}"
          DESC="${{ steps.issue-parser.outputs.issueparser_description }}"

          [ -n "$NAME" ] && [ -n "$URL" ] && [ -n "$DESC" ] || { echo "Missing fields"; exit 1; }
          echo "$URL" | grep -Eqi '^https?://$|^https?://.+' || { echo "URL must start with http(s)://"; exit 1; }

          echo "NAME=$NAME" >> $GITHUB_ENV
          echo "URL=$URL" >> $GITHUB_ENV
          echo "DESC=$DESC" >> $GITHUB_ENV

      - name: Prevent duplicates (by name or url)
        run: |
          DUPS=$(yq -r --arg n "$NAME" --arg u "$URL" \
            '[ .[] | select(.name == $n or .url == $u) ] | length' _data/communities.yml)
          [ "$DUPS" = "0" ] || { echo "Duplicate name or URL"; exit 1; }

      - name: Append entry
        env:
          SOURCE: "issue #${{ github.event.issue.number }} by @${{ github.event.issue.user.login }}"
        run: |
          yq -oy -i '. += [{
            "name": env(NAME),
            "url": env(URL),
            "description": env(DESC),
            "source": env(SOURCE)
          }]' _data/communities.yml

      - name: Sort by name
        run: |
          yq -oy 'sort_by(.name)' _data/communities.yml > _data/communities.sorted.yml
          mv _data/communities.sorted.yml _data/communities.yml

      - name: Create or update PR (draft = approval gate)
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "add-community/issue-${{ github.event.issue.number }}"
          commit-message: "Add community from issue #${{ github.event.issue.number }}"
          title: "Add community: ${{ env.NAME }} (from #${{ github.event.issue.number }})"
          body: |
            Generated from issue #${{ github.event.issue.number }}.

            **Proposed entry**
            - **Name:** ${{ env.NAME }}
            - **URL:**  ${{ env.URL }}
            - **Description:** ${{ env.DESC }}
            - **Source:** issue #${{ github.event.issue.number }} by @${{ github.event.issue.user.login }}

            Maintainers: review/merge to incorporate.
          labels: community:automation
          add-paths: _data/communities.yml
          draft: true
          delete-branch: false
